main: g.test.Main
name: API_TEST
version: 1.1
depend: [MAA]
api-version: 1.13
commands:
   create:
      description: Test
      usage: /create <player> | Creates a challenge for a player!
    